import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const format = req.nextUrl.searchParams.get('format') || 'json'

  const scan = await prisma.scan.findUnique({
    where: { id },
    include: {
      findings: { orderBy: [{ severity: 'asc' }] },
      pages: { select: { url: true, statusCode: true, title: true, depth: true } },
    },
  })

  if (!scan) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  if (format === 'json') {
    return new NextResponse(JSON.stringify(scan, null, 2), {
      headers: {
        'Content-Type': 'application/json',
        'Content-Disposition': `attachment; filename="scan-${id}.json"`,
      },
    })
  }

  const severityColor: Record<string, string> = {
    high: '#dc2626', medium: '#d97706', low: '#2563eb', info: '#6b7280',
  }

  const findingsHtml = scan.findings.map(f => `
    <div style="border:1px solid #e5e7eb;border-radius:6px;padding:16px;margin-bottom:12px;">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
        <span style="background:${severityColor[f.severity] || '#6b7280'};color:white;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;text-transform:uppercase">${f.severity}</span>
        <span style="font-size:12px;color:#6b7280;background:#f3f4f6;padding:2px 8px;border-radius:4px;">${f.category}</span>
        <strong>${f.title}</strong>
      </div>
      <p style="color:#374151;margin:0 0 8px">${f.description}</p>
      <p style="color:#6b7280;font-size:13px;margin:0 0 8px">URL: ${f.url}</p>
      <pre style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:4px;padding:8px;font-size:12px;overflow:auto;white-space:pre-wrap">${f.evidence}</pre>
    </div>`).join('')

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Security Scan Report - ${scan.targetUrl}</title>
<style>body{font-family:system-ui,sans-serif;max-width:900px;margin:0 auto;padding:24px;color:#111}</style>
</head><body>
<h1>Site Security Review Report</h1>
<p><strong>Target:</strong> ${scan.targetUrl}</p>
<p><strong>Status:</strong> ${scan.status}</p>
<p><strong>Scanned:</strong> ${scan.finishedAt?.toISOString() || 'In progress'}</p>
<hr>
<h2>Summary</h2>
<table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse">
<tr><th>High</th><th>Medium</th><th>Low</th><th>Info</th><th>Pages</th></tr>
<tr><td>${scan.highCount}</td><td>${scan.mediumCount}</td><td>${scan.lowCount}</td><td>${scan.infoCount}</td><td>${scan.pagesScanned}</td></tr>
</table>
<h2>Findings (${scan.findings.length})</h2>
${findingsHtml || '<p>No findings.</p>'}
<hr><p style="color:#9ca3af;font-size:12px">Generated by Site Security Review Scanner &bull; For authorized testing only</p>
</body></html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `attachment; filename="scan-${id}.html"`,
    },
  })
}
